output_folder:              evaluating_calls_output_snippy

pandora_vcf_ref:            data/pandora_multisample.vcf_ref.fa
truth_assemblies:           metadata/truth_assemblies.csv
references:                 metadata/references_snippy.csv

pandora_eval_config:
  output_folder: data/analysis_output_pandora_no_filters_snippy_all_precision_flank_150_recall_flank_25_truth_probes_flank_21
  tool:                       snippy
  coverage:                   all
  coverage_filter:            0
  strand_bias_filter:         Not_App
  gaps_filter:                Not_App