output_folder:              evaluating_snippy_calls_output
pandora_vcf_ref:            data/pandora_multisample.vcf_ref.fa
truth_assemblies:           metadata/truth_assemblies.csv
references:                 metadata/references.csv
pandora_eval_output_folder: data/analysis_output_pandora_default_filters_snippy_all_bwa_seed_11
