output_folder:              evaluating_snippy_calls_output
pandora_vcf_ref:            data/pandora_multisample.vcf_ref.fa
truth_assemblies:           metadata/truth_assemblies.csv
references:                 metadata/references.csv
# pandora_evaluation_folder:  data/analysis_output
